blue1:
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 20

    left_arm_base_to_left_arm_controller:
        type: effort_controllers/JointPositionController
        joint: left_arm_base_to_left_arm
        pid: {p: 50.0, i: 1.0, d: 0.0}
    right_arm_base_to_right_arm_controller:
        type: effort_controllers/JointPositionController
        joint: right_arm_base_to_right_arm
        pid: {p: 50.0, i: 1.0, d: 0.0}

red1:
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 20

    left_arm_base_to_left_arm_controller:
        type: effort_controllers/JointPositionController
        joint: left_arm_base_to_left_arm
        pid: {p: 50.0, i: 1.0, d: 0.0}
    right_arm_base_to_right_arm_controller:
        type: effort_controllers/JointPositionController
        joint: right_arm_base_to_right_arm
        pid: {p: 50.0, i: 1.0, d: 0.0}

green1:
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 20

    left_arm_base_to_left_arm_controller:
        type: effort_controllers/JointPositionController
        joint: left_arm_base_to_left_arm
        pid: {p: 50.0, i: 1.0, d: 0.0}
    right_arm_base_to_right_arm_controller:
        type: effort_controllers/JointPositionController
        joint: right_arm_base_to_right_arm
        pid: {p: 50.0, i: 1.0, d: 0.0}